/**
 * PopChoice - Movie Recommendation App
 * Main application logic for screen navigation and form handling
 */

import { openai, supabase } from './config.js';

// Constants
const SCREEN_IDS = {
    QUESTIONS: 'screen1',
    RESULTS: 'screen2'
};

const INPUT_IDS = {
    FAVORITE_MOVIE: 'favoriteMovieInput',
    MOOD: 'moodInput',
    FUN: 'funInput'
};

const BUTTON_IDS = {
    LETS_GO: 'letsGoButton',
    GO_AGAIN: 'goAgainButton'
};

// DOM Elements (will be set in init)
let screen1, screen2;

/**
 * Shows the specified screen and hides all others
 * @param {number} screenNumber - The screen number to display (1 or 2)
 */
function showScreen(screenNumber) {
    // Hide all screens
    screen1.classList.remove('active');
    screen2.classList.remove('active');
    
    // Show the requested screen
    if (screenNumber === 1) {
        screen1.classList.add('active');
        resetForm();
    } else if (screenNumber === 2) {
        screen2.classList.add('active');
    }
}

/**
 * Gets user input from all form fields and combines them
 * @returns {string} Combined user input string
 */
function getUserInput() {
    const favoriteMovie = document.getElementById(INPUT_IDS.FAVORITE_MOVIE)?.value.trim() || '';
    const mood = document.getElementById(INPUT_IDS.MOOD)?.value.trim() || '';
    const fun = document.getElementById(INPUT_IDS.FUN)?.value.trim() || '';
    
    // Combine all inputs into a single query string
    const parts = [];
    if (favoriteMovie) parts.push(`Favorite movie: ${favoriteMovie}`);
    if (mood) parts.push(`Mood preference: ${mood}`);
    if (fun) parts.push(`Entertainment preference: ${fun}`);
    
    return parts.join('. ') || 'What movie should I watch?';
}

/**
 * Resets all form inputs on the questions screen
 */
function resetForm() {
    const inputs = [
        document.getElementById(INPUT_IDS.FAVORITE_MOVIE),
        document.getElementById(INPUT_IDS.MOOD),
        document.getElementById(INPUT_IDS.FUN)
    ];

    inputs.forEach(input => {
        if (input) {
            input.value = '';
        }
    });
}

/**
 * Creates an embedding from user input and finds semantically matching movie
 * @param {string} input - Combined user input text
 */
async function findMovieRecommendation(input) {
    try {
        // Show loading state
        displayMovieRecommendation('Loading...', 'Finding your perfect movie match...');
        
        // Create a vector embedding representing the input text
        const embeddingResponse = await openai.embeddings.create({
            model: "text-embedding-ada-002",
            input,
        }); 
        
        // The vector generated by OpenAI
        const embedding = embeddingResponse.data[0].embedding;
        
        // Query Supabase for nearest vector match
        const { data, error } = await supabase.rpc('match_movies', {
            query_embedding: embedding,
            match_threshold: 0.50,
            match_count: 1
        });
        
        if (error) {
            console.error('Error fetching movie recommendation:', error);
            displayMovieRecommendation('Error', 'Unable to find a movie recommendation. Please try again.');
            return;
        }
        
        if (data && data.length > 0) {
            // Extract movie title and description from content
            const content = data[0].content;
            const similarity = data[0].similarity;
            
            // Try to extract title and year from content (format: "Title (Year): Description")
            const titleMatch = content.match(/^([^(]+)\s*\((\d{4})\)/);
            const title = titleMatch ? `${titleMatch[1].trim()} (${titleMatch[2]})` : 'Movie Recommendation';
            const description = content.replace(/^[^(]+\(\d{4}\)[:\s]*/, '').trim();
            
            displayMovieRecommendation(title, description);
        } else {
            displayMovieRecommendation('No Match Found', 'We couldn\'t find a movie that matches your preferences. Please try again with different inputs.');
        }
    } catch (error) {
        console.error('Error in findMovieRecommendation:', error);
        displayMovieRecommendation('Error', 'An error occurred while finding your movie recommendation. Please try again.');
    }
}

/**
 * Displays movie recommendation on screen 2
 * @param {string} title - Movie title
 * @param {string} description - Movie description
 */
function displayMovieRecommendation(title, description) {
    const titleElement = document.querySelector('#screen2 .movie-title');
    const descriptionElement = document.querySelector('#screen2 .movie-description');
    
    if (titleElement) {
        titleElement.textContent = title;
    }
    if (descriptionElement) {
        descriptionElement.textContent = description;
    }
}

/**
 * Initializes event listeners for navigation buttons
 */
function initializeNavigation() {
    const letsGoButton = document.getElementById(BUTTON_IDS.LETS_GO);
    const goAgainButton = document.getElementById(BUTTON_IDS.GO_AGAIN);
    
    if (letsGoButton) {
        console.log('Attaching click handler to Let\'s Go button');
        letsGoButton.addEventListener('click', async (e) => {
            e.preventDefault();
            e.stopPropagation();
            console.log('Let\'s Go button clicked!');
            
            try {
                // Get user input from all fields
                const userInput = getUserInput();
                console.log('User input collected:', userInput);
                
                // Show screen 2 immediately
                console.log('Switching to screen 2...');
                showScreen(2);
                console.log('Screen 2 should now be visible');
                
                // Find and display movie recommendation
                console.log('Starting movie recommendation search...');
                await findMovieRecommendation(userInput);
            } catch (error) {
                console.error('Error in button click handler:', error);
                console.error('Error stack:', error.stack);
                // Still show screen 2 even if there's an error
                showScreen(2);
                displayMovieRecommendation('Error', `An error occurred: ${error.message}. Please check the console for details.`);
            }
        });
        console.log('Click handler attached successfully');
    } else {
        console.error('Let\'s Go button not found! Button ID:', BUTTON_IDS.LETS_GO);
    }
    
    if (goAgainButton) {
        goAgainButton.addEventListener('click', () => showScreen(1));
    }
}

/**
 * Initialize the application when DOM is ready
 */
function init() {
    console.log('Initializing app...');
    
    // Get DOM elements now that DOM is ready
    screen1 = document.getElementById(SCREEN_IDS.QUESTIONS);
    screen2 = document.getElementById(SCREEN_IDS.RESULTS);
    
    console.log('Screen1 element:', screen1);
    console.log('Screen2 element:', screen2);
    
    if (!screen1 || !screen2) {
        console.error('Screen elements not found! Check HTML structure.');
        return;
    }
    
    const letsGoButton = document.getElementById(BUTTON_IDS.LETS_GO);
    console.log('Let\'s Go button found:', letsGoButton);
    
    if (!letsGoButton) {
        console.error('Let\'s Go button not found! Check HTML.');
        return;
    }
    
    initializeNavigation();
    showScreen(1);
    
    console.log('App initialized successfully');
}

// Start the application when DOM is loaded
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
} else {
    // DOM is already ready
    init();
}

// Export for potential future use
export { showScreen };
